### PR TITLE
Update data.inc.php

### PR DESCRIPTION
**Pull request by arshidkv12**
Array has 2 duplicate keys - 'supports'

### CODE REVIEW

**Comment by TobiasBg** [comment]
Hi @arshidkv12,

thanks! Merged in a76fa5d6d6d034fc09456cfc91c528e2497f2ebc.

Just out of curiosity: Are you using some kind of tool to find such errors, or the issue with `str_pad()` in #156?

Best wishes,
Tobias

**Comment by arshidkv12** [comment]
I think, You removed 'support' keys (line number 66 also.) . I think, it will make error.

**Comment by TobiasBg** [comment]
Hi @arshidkv12,

I'm not sure that I understand. I removed the same code that you suggest, I just chose the other/same line, because I could then revert the commit that accidentally introduced this. (I actually already had this fixed in another (non-public) branch, so that cherry-picking was easier than merging). What do you mean that this could cause errors?

For other changes, I will be more than happy to directly merge them, of course, except maybe for some adjusted commit messages.

And again just out of curiosity: Are you using some kind of tool to find such errors, like this or the issue with `str_pad()` in #156?

Regards,
Tobias

**Comment by arshidkv12** [comment]
I am using vs code linter.

**Comment by TobiasBg** [comment]
Hi!

Ah, cool! I really need to look into that :-)
Thanks for your contributions!

Best wishes,
Tobias

**Comment by arshidkv12** [comment]
Use https://phpstan.org/ also.

**Pull request closed without merging**
