### PR TITLE
i18n improvments

### PR DESCRIPTION
**Pull request by ramiy**

### CODE REVIEW

**Comment by TobiasBg** [comment]
Hi @ramiy,

great work, thanks a lot! I'll merge this in in the next iteration!

Best wishes,
Tobias

**Comment by ramiy** [comment]
@TobiasBg Any updates?

**Comment by TobiasBg** [comment]
Hi @ramiy, sorry, not yet. I've been rather busy over the last weeks, but I have plans on revising the strings/translations in all of TablePress soon, including your changes.

**Comment by ramiy** [comment]
@TobiasBg Contact me when you do, I will help.

**Comment by TobiasBg** [comment]
Hi,

I finally got around to merging these in, in commits 7b565ad40ab232ce88c1b99357c6693424ecf29d, 22a6edb0ae44db9413513eeb1dabf1e9ceeaf1df, and ee128e265f9a1f7c3c141416ed4e05cecbf9ff25.
Thanks for your contribution!

Tobias

**Pull request closed without merging**
