### PR TITLE
Add Portuguese translation (pt_PT)

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by TobiasBg** [comment]
Hi @pedro-mendonca,

thanks for submitting this PR!

Now, as WordPress is making the so-called "Language Packs" feature available for plugins as well, which means that translations for plugins can be updated more easily in the future and won't even require a new release of the plugin, I'd prefer to directly start on that infrastructure.
WordPress is introducing this workflow to popular and active plugins first, and I'm quite happy that TablePress is on that list! :-) (For technical details, you can read more [here](https://make.wordpress.org/plugins/2015/09/01/plugin-translations-on-wordpress-org/).)

So, in the future, instead of having to deal with .po and .mo files via email, the translations can simply be done directly on a website, at https://translate.wordpress.org/projects/wp-plugins/tablepress.
Additionally, it will be able to translate the texts that are used in the WordPress Plugin Directory, so that pages like https://de.wordpress.org/plugins/tablepress/ will soon be available in other languages as well.
As you seem to be interested in helping with the translation, I'd gladly like to get you involved in this process as well, if you want. All that is necessary is an account on wordpress.org (which you might already have). With that, you can add suggestions for translations, and I'd also like to make you a validator for your language, who can approve translation suggestions that other people make. With this process, we can send more accurate and up-to-date translations to the users more easily.

Would you be interested in that? If so, please send me your wordpress.org username and I will try to get the infrastructure set up for you.

**Comment by pedro-mendonca** [comment]
Hi @TobiasBg 

In fact I'm already a validator in pt_PT WordPress locale.
As the WordPress translation site is still giving it's first steps and I don't know what developers prefer, I did pushed the translation here at GitHub and also pushed it in the https://translate.wordpress.org/locale/pt/default/wp-plugins/tablepress.
I really don't know how developers and authors will deal with this, wich system will get priority ef different translations are inserted, etc.
So, for now you have both :)
Thanks, this plugin really rules!

**Comment by TobiasBg** [comment]
Hi @pedro-mendonca!

Perfect! :-) That's great, thanks! With this, user who use the `pt_PT` locale in WordPress will actually already get your translation, i.e. I won't even have to ship the files :-)
In fact, I'm planning to remove all included .po and .mo files from TablePress in the next release, and with that completely switch to the translate.wordpress.org process.

So, thanks a lot for your contributions there! It would be great to have you on board for future translation updates of TablePress!

**Comment by pedro-mendonca** [comment]
I'll keep tracking the changes here and make any contributions I can, debugging translations and strings related issues.
I've pushed a small add to the list of available languages in the Plugin Options also, not just the .po/.mo files. Do you want me to push just that file?

**Comment by TobiasBg** [comment]
No, that's fine. I'm not sure yet how to handle that list of translators. I might remove it as well, or move it to the tablepress.org website, but in any case, I'll get the information from here.

**Comment by pedro-mendonca** [comment]
ok than :+1:

**Comment by pedro-mendonca** [comment]
One more question.
I've been dealing with this issues of developers having both ways to input translations. I didn't saw any plugin having it's localizations updated. Do you know what it takes to the updates start to work from the wordpress translation site?

**Comment by TobiasBg** [comment]
From what I know, plugin language packs are generated (once or twice a day) for all locales of a plugin that are at 100%. They are updated through the regular auto update mechanism, but it might be necessary to visit the "Updates" page in WordPress.
But all my knowledge is just from https://make.wordpress.org/plugins/2015/09/01/plugin-translations-on-wordpress-org/ and one quick self-test with German (where I simply deleted the tablepress-de_DE.mo|po files and still got the German translation, as they were download to wp-content/languages/plugins/.

**Comment by pedro-mendonca** [comment]
Ok thanks
I'll do some testing later on this.

**Pull request closed without merging**
