### PR TITLE
Should Exit Early

### PR DESCRIPTION
**Pull request by beoss**
Minor feature to allow plugin to be enabled via a filter if being run via CRON or something that would typically cause TablePress to exit early.

### CODE REVIEW

**Comment by TobiasBg** [comment]
Hi @beoss,

thanks for this PR! Out of curiosity: What's your exact use case for this, i.e. what are you doing that would benefit from this?

Regards,
Tobias

**Comment by beoss** [comment]
Hi @TobiasBg ,

My use case is to run TablePress via CRON.  I have usage scenario where I need to generate a table and the action is performed via a CRON job.

Regards,
Thomas

**Comment by TobiasBg** [comment]
Hi @beoss,

thanks for the clarification! Are there specific parts of TablePress that you would need inside a Cron job? Are you using the Shortcode or template tag functions or maybe even the admin interface somehow?
(I'm asking as I'm working on improving the load process in general.)

Best wishes,
Tobias

**Comment by TobiasBg** [comment]
Hi,

thanks! This has now been integrated in the beta release of TablePress 2.0 (not yet pushed to this repository). The hook name is `tablepress_exit_early`.
Please see https://tablepress.org/8-million-downloads-tablepress-2-0/

Best wishes,
Tobias

**Pull request closed without merging**
